org.gradle.jvmargs=-Xmx4G -XX:+UseG1GC -Dfile.encoding=UTF-8
org.gradle.java.home=C:/Users/28585/AppData/Roaming/.minecraft/runtime/java-runtime-delta
org.gradle.daemon=true
org.gradle.caching=true
org.gradle.vfs.watch=true
org.gradle.workers.max=8
org.gradle.parallel=true
org.gradle.configureondemand=true

minecraft_version=1.21.11
yarn_mappings=1.21.11+build.6
loader_version=0.19.5
fabric_version=0.141.6+1.21.11

mod_version=0.1.0
maven_group=cn.frkovo
archives_base_name=rhythmc-maker
owo_version=0.13.0+1.21.11
